import { bool } from 'prop-types';
import moment from 'moment';
import React from 'react';

export const COLUMN_CONFIG = [
  {
    field: 'timestamp',
    headerName: 'Occurred On',
    description: 'Event Timestamp',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    type: 'dateTime',
    minWidth: 170,
    flex: 1,
    valueFormatter: (params) => {
      return moment(params.value).format('YYYY-MM-DD hh:mm A');
    },
  },
  {
    field: 'certainty',
    headerName: 'Certainty',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
    minWidth: 85,
    flex: 1,
  },
  {
    field: 'severity',
    headerName: 'Severity',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
    minWidth: 85,
    flex: 1,
  },
  {
    field: 'score',
    headerName: 'Score',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    align: 'center',
    headerAlign: 'center',
    type: 'number',
    minWidth: 75,
    flex: 1,
  },
  {
    field: 'category',
    headerName: 'Category',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 200,
  },
  {
    field: 'admin_state',
    headerName: 'Status',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    valueFormatter: (params) => {
      return camelCaseToSentence(params.value, true);
    },
    minWidth: 150,
    flex: 1,
  },
  {
    field: 'entry_type',
    headerName: 'Type',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    valueFormatter: (params) => {
      return camelCaseToSentence(params.value, true);
    },
    minWidth: 150,
    flex: 1,
  },
  {
    field: 'entry_origin',
    headerName: 'Entry Origin',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 200,
    flex: 1,
  },
  {
    field: 'entry_source',
    headerName: 'Entry Source',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 200,
    flex: 1,
  },
  {
    field: 'timestamp',
    headerName: 'Occurred On',
    description: 'Event Timestamp',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    type: 'dateTime',
    minWidth: 170,
    flex: 1,
    valueFormatter: (params) => {
      return moment(params.value).format('YYYY-MM-DD hh:mm A');
    },
  },
  {
    field: 'trigger',
    headerName: 'Trigger',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 250,
    flex: 1,
    cellClassName: 'multi-row',
  },
  {
    field: 'entity_type',
    headerName: 'Entity Type',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 100,
    flex: 1,
  },
  {
    field: 'src',
    headerName: 'Source',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 250,
    flex: 1,
  },
  {
    field: 'dest',
    headerName: 'Destination',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 250,
    flex: 1,
  },
  {
    field: 'case_id',
    headerName: 'Case Id',
    type: 'number',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 130,
    flex: 1,
  },
  {
    field: 'case_summary',
    headerName: 'Case Summary',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 300,
    flex: 1,
    cellClassName: 'multi-row',
  },
  {
    field: 'case_detail',
    headerName: 'Case Details',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 400,
    flex: 1,
    cellClassName: 'multi-row',
  },
  {
    field: 'entity_uuid',
    headerName: 'Entity UUID',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 200,
    flex: 1,
    cellClassName: 'multi-row',
  },
  {
    field: 'ioa_count',
    headerName: 'IOA Count',
    type: 'number',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 100,
    flex: 1,
  },
  {
    field: 'last_modified',
    headerName: 'Updated On',
    type: 'dateTime',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 170,
    flex: 1,
    valueFormatter: (params) => {
      return moment(params.value).format('YYYY-MM-DD hh:mm A');
    },
  },
  {
    field: 'created_at',
    headerName: 'Created On',
    type: 'dateTime',
    renderHeader: (params) => <strong> {params?.colDef?.headerName ?? 'Undefined'} </strong>,
    minWidth: 170,
    flex: 1,
    valueFormatter: (params) => {
      return moment(params.value).format('YYYY-MM-DD hh:mm A');
    },
  },
];

export const camelCaseToSentence = (camelStr, capitalizeAllWords) => {
  if (!camelStr) return camelStr;
  return camelStr.replace(/^[a-z]|[A-Z]/g, function (v, i) {
    return i === 0 ? v.toUpperCase() : ' ' + (capitalizeAllWords ? v.toUpperCase() : v.toLowerCase());
  });
};

export const IncidentColumns = [
  { field: 'timestamp', headerName: 'Timestamp', type: 'string', width: 180 },
  { field: 'case_id', headerName: 'Case ID', type: 'number', width: 100 },
  { field: 'certainty', headerName: 'Certainty', type: 'number', width: 100 },
  { field: 'severity', headerName: 'Severity', type: 'number', width: 100 },
  { field: 'victim_user_uuid', headerName: 'Target User', type: 'string', width: 150, hide: true },
  { field: 'victim_host_uuid', headerName: 'Target Host', type: 'string', width: 120, hide: true },
  { field: 'attacker_user_uuid', headerName: 'Actor User', type: 'string', width: 120, hide: true },
  { field: 'attacker_host_uuid', headerName: 'Actor Host', type: 'string', width: 120, hide: true },
  { field: 'case_summary', headerName: 'Summary', type: 'String', width: 600, cellClassName: 'multi-row' },
  { field: 'category', headerName: 'Category', type: 'string', width: 180 },
  { field: 'score', headerName: 'Score', type: 'string', width: 80 },
  { field: 'created-at', headerName: 'Created At', type: 'string', width: 160 },
  { field: 'entry_origin', headerName: 'Entry Origin', type: 'string', width: 200 },
  { field: 'entry_source', headerName: 'Entry Source', type: 'string', width: 120 },
  { field: 'entry_type', headerName: 'Entry Type', type: 'string', width: 130 },
  { field: 'entry_uuid', headerName: 'Entry UUID', type: 'string', width: 160, cellClassName: 'multi-row' },
  { field: 'victim_is_src', headerName: 'Target Src', type: 'string', width: 110 },
  { field: 'recommendation', headerName: 'Recommentation', type: 'string', width: 500, cellClassName: 'multi-row' },
  { field: 'dest', headerName: 'Dest', type: 'string', width: 140 },
  { field: 'case_detail', headerName: 'Details', type: 'String', width: 600, cellClassName: 'multi-row' },
  { field: 'victim_ip', headerName: 'Target IP', type: 'string', width: 130 },
  { field: 'admin_state', headerName: 'Admin State', type: 'string', width: 150 },
  { field: 'last_modified', headerName: 'Last Modified', type: 'string', width: 170 },
  { field: 'attacker_is_dest', headerName: 'Actor is Dest', type: 'string', width: 120, hide: true },
  { field: 'attacker_ip', headerName: 'Actor IP', type: 'string', width: 130 },
  { field: 'src', headerName: 'Src', type: 'string', width: 130 },
  { field: 'ioa_count', headerName: 'Src', type: 'string', width: 130 },
  { field: 'entity_type', headerName: 'Entity Type', type: 'string', width: 150 },
  { field: 'main_event', headerName: 'Entity', type: 'string', width: 140 },
  { field: 'positive', headerName: 'Positive', type: bool, width: 120 },
];

export const caseColumns = [
  { field: 'Timestamp', headerName: 'timestamp', type: 'string', width: 180 },
  { field: 'Category', headerName: 'Category', type: 'string', width: 180 },
  { field: 'AdminState', headerName: 'Admin State', type: 'string', width: 150 },
  { field: 'Certainty', headerName: 'Certainty', type: 'number', width: 100 },
  { field: 'Severity', headerName: 'Severity', type: 'number', width: 100 },
  { field: 'TargetUser', headerName: 'Target User', type: 'string', width: 150, hide: true },
  { field: 'TargetHost', headerName: 'Target Host', type: 'string', width: 120, hide: true },
  { field: 'ActorUser', headerName: 'Actor User', type: 'string', width: 120, hide: true },
  { field: 'ActorHost', headerName: 'Actor Host', type: 'string', width: 120, hide: true },
  { field: 'CaseID', headerName: 'Case ID', type: 'number', width: 100 },
  { field: 'Score', headerName: 'Score', type: 'string', width: 80 },
  { field: 'ActorIP', headerName: 'Actor IP', type: 'number', width: 150 },
  { field: 'Summary', headerName: 'Summary', type: 'String', width: 600, cellClassName: 'multi-row' },
  { field: 'LastModified', headerName: 'Last Modified', type: 'string', width: 170 },
  { field: 'ActorisDest', headerName: 'Actor is Dest', type: 'number', width: 120, hide: true },
  { field: 'CreatedAt', headerName: 'Created At', type: 'string', width: 160 },
  { field: 'EntryOrigin', headerName: 'Entry Origin', type: 'string', width: 120 },
  { field: 'EntrySource', headerName: 'Entry Source', type: 'string', width: 120 },
  { field: 'EntryType', headerName: 'Entry Type', type: 'string', width: 110 },
  { field: 'EntryUUID', headerName: 'Entry UUID', type: 'string', width: 160, cellClassName: 'multi-row' },
  { field: 'TargetSrc', headerName: 'Target Src', type: 'string', width: 110, hide: true },
  { field: 'Positive', headerName: 'Positive', type: bool, width: 120 },
  { field: 'Recommentation', headerName: 'Recommentation', type: 'string', width: 300, cellClassName: 'multi-row' },
  { field: 'Dest', headerName: 'Dest', type: 'string', width: 140 },
  { field: 'Details', headerName: 'Details', type: 'String', width: 400, cellClassName: 'multi-row' },
  { field: 'TargetIP', headerName: 'Target IP', type: 'string', width: 130 },
  { field: 'Src', headerName: 'Src', type: 'number', width: 130 },
  { field: 'Entity', headerName: 'Entity', type: 'string', width: 140 },
  { field: 'EntityType', headerName: 'Entity Type', type: 'string', width: 150 },
];

export const policyColumns = [
  { field: 'Timestamp', headerName: 'Timestamp', type: 'string', width: 180 },
  { field: 'Certainty', headerName: 'Certainty', type: 'number', width: 100 },
  { field: 'Severity', headerName: 'Severity', type: 'number', width: 100 },
  { field: 'TargetUser', headerName: 'Target User', type: 'string', width: 150, hide: true },
  { field: 'TargetHost', headerName: 'Target Host', type: 'string', width: 120, hide: true },
  { field: 'ActorUser', headerName: 'Actor User', type: 'string', width: 120, hide: true },
  { field: 'ActorHost', headerName: 'Actor Host', type: 'string', width: 120, hide: true },
  { field: 'Score', headerName: 'Score', type: 'string', width: 80 },
  { field: 'Summary', headerName: 'Summary', type: 'String', width: 600, cellClassName: 'multi-row' },
  { field: 'Category', headerName: 'Category', type: 'string', width: 180 },
  { field: 'ActorisDest', headerName: 'Actor is Dest', type: 'string', width: 120, hide: true },
  { field: 'CreatedAt', headerName: 'Created At', type: 'string', width: 160 },
  { field: 'EntryOrigin', headerName: 'Entry Origin', type: 'string', width: 120 },
  { field: 'EntrySource', headerName: 'Entry Source', type: 'string', width: 120 },
  { field: 'EntryType', headerName: 'Entry Type', type: 'string', width: 110 },
  { field: 'EntryUUID', headerName: 'Entry UUID', type: 'string', width: 160, cellClassName: 'multi-row' },
  { field: 'TargetSrc', headerName: 'Target Src', type: 'string', width: 110, hide: true },
  { field: 'Positive', headerName: 'Positive', type: bool, width: 120 },
  { field: 'Recommentation', headerName: 'Recommentation', type: 'string', width: 500, cellClassName: 'multi-row' },
  { field: 'Dest', headerName: 'Dest', type: 'string', width: 140 },
  { field: 'Details', headerName: 'Details', type: 'String', width: 600, cellClassName: 'multi-row' },
  { field: 'TargetIP', headerName: 'Target IP', type: 'string', width: 130 },
  { field: 'AdminState', headerName: 'Admin State', type: 'string', width: 150 },
  { field: 'LastModified', headerName: 'Last Modified', type: 'string', width: 170 },
  { field: 'ActorIP', headerName: 'Actor IP', type: 'string', width: 120 },
  { field: 'CaseID', headerName: 'Case ID', type: 'number', width: 100 },
  { field: 'Src', headerName: 'Src', type: 'string', width: 130 },
];

export const testRowData = [
  {
    id: 1,
    actorip_addr: '10.3.0.2',
    admin_state: 'IncidentReported',
    case_detail: 'This is mistnet test generated daily',
    case_id: 797,
    case_summary: 'MistNet Test Incident has been triggered from 10.3.18.237',
    category: 'Test',
    certainty: 40,
    created_at: 1637020807464,
    dest: '10.3.0.2',
    entity_type: 'Host',
    entity_uuid: 'ip-10-3-18-237.us-west-2.compute.internal',
    entry_origin: 'Network Analysis Engine',
    entry_source: 'test101-aws-0-0',
    entry_type: 'TriggerEvent',
    entry_uuid: '2d3426be-1102-4f89-b181-1497828f750c',
    ioa_count: 1,
    last_modified: 1637020807464,
    positive: true,
    recommendation:
      'SUMMARY. Time taken for incident creation: 5951 msec. &nbsp;&nbsp;&nbsp;&nbsp;Event origination time: 2021-11-15 16:00:01 -0800 PST (2021-11-16T00:00:01Z). &nbsp;&nbsp;&nbsp;&nbsp;Incident creation time: 2021-11-15 16:00:07 -0800 PST (2021-11-16T00:00:07Z)',
    score: 5,
    severity: 50,
    src: '10.3.18.237',
    targets: Array(1),
    action: 'MistNet Behavior Engine Test',
    host_uuid: 'ip-10-3-18-237.us-west-2.compute.internal',
    ip_addr: '10.3.18.237',
    timestamp: 1637020801513,
    trigger: 'MistNet Behavior Engine Test',
  },
  {
    id: 2,
    Timestamp: 'Thu Jan 13, 11:57:37',
    CaseID: 919,
    Certainty: 50,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Vulnerable Java Version 1.6.x Detected detected in a network session from source IP 192.168.1.107 to destination IP 23.227.189.102',
    Category: 'Vulnerability',
    Score: 8,
    CreatedAt: 'Thu Jan 13, 12:07:57',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'ee73f42c-f0c6-43fb-93c6-25f6a361a3e0',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.',
    Dest: '23.227.189.102',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '192.168.1.107',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 16:33:28',
    ActorisDest: 'null',
    ActorIP: '23.227.189.102',
    Src: '192.168.1.107',
    EntityType: 'Ip',
    Entity: '192.168.1.107',
    Positive: true,
  },
  {
    id: 3,
    Timestamp: 'Wed Jan 12, 20:20:03',
    CaseID: 875,
    Certainty: 75,
    Severity: 50,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Possible attack Possible CVE-2021-44228 Payload via LDAPv3 Response against 172.16.0.60 detected from 178.62.55.188',
    Category: 'Service Attack',
    Score: 9,
    CreatedAt: 'Wed Jan 12, 19:30:18',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'aacb17ba-c91d-4a67-9627-2cd160969ae4',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination',
    Dest: '172.16.0.60',
    Details:
      'Remote attackers are attempting to compromise a service. If vulnerabilities are successfully exploited, they could start lateral movement, data exfiltration, etc. We recommend examining the server logs for any signs of a potential compromise.',
    TargetIP: '172.16.0.60',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 19:30:30',
    ActorisDest: 'null',
    ActorIP: '178.62.55.188',
    Src: '178.62.55.188',
    EntityType: 'Ip',
    Entity: '172.16.0.60',
    Positive: true,
  },
  {
    id: 4,
    Timestamp: 'Wed Jan 12, 20:20:03',
    CaseID: 873,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Possible attack Possible CVE-2021-44228 Payload via LDAPv3 Response against 172.16.0.60 detected from 178.62.55.188',
    Category: 'Service Attack',
    Score: 10,
    CreatedAt: 'Wed Jan 12, 17:30:16',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '5f5fdaf0-3b54-4739-bf13-62c678804edf',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '172.16.0.60',
    Details:
      'Remote attackers are attempting to compromise a service. If vulnerabilities are successfully exploited, they could start lateral movement, data exfiltration, etc. We recommend examining the server logs for any signs of a potential compromise.',
    TargetIP: '172.16.0.60',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 19:30:24',
    ActorisDest: 'null',
    ActorIP: '178.62.55.188',
    Src: '178.62.55.188',
    EntityType: 'Ip',
    Entity: '178.62.55.188',
    Positive: true,
  },
  {
    id: 5,
    Timestamp: 'Tue Jan 11, 16:54:54',
    CaseID: 648,
    Certainty: 50,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex) has been detected on source IP 5.61.34.51 to destination IP 10.11.21.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 17:05:56',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '3dac7c9c-e861-4baa-8e6a-111663ae0b56',
    TargetSrc: 'null',
    Recommentation:
      'Verify if any of the following signs of infection are present (some might be missing due to the endpoint being outside of monitored network): suspicious/malicious file download, callback to C&C domain, suspicious activity on the system, unexpected outbound network activity from the source to internal/external hosts. If infection is confirmed, contact the user to take the endpoint offline for malware cleanup or reimage.',
    Dest: '10.11.21.101',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '5.61.34.51',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 17:05:56',
    ActorisDest: 'null',
    ActorIP: '10.11.21.101',
    Src: '5.61.34.51',
    EntityType: 'Ip',
    Entity: '5.61.34.51',
    Positive: true,
  },
  {
    id: 6,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 539,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 195.123.220.86 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 7,
    CreatedAt: 'Tue Jan 11, 11:22:43',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd2e7a925-26c2-485c-8a85-b2cdb97b21d8',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '195.123.220.86',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.220.86',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:19',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.220.86',
    Positive: true,
  },
  {
    id: 7,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 551,
    Certainty: 75,
    Severity: 100,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 37.228.117.247 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 11:22:43',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd2e7a925-26c2-485c-8a85-b2cdb97b21d8',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination',
    Dest: '195.123.220.86',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.220.86',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:19',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.220.86',
    Positive: true,
  },
  {
    id: 8,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 551,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 37.228.117.247 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 11:26:02',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '05fa9f13-c9b1-43a6-a6f7-c9818befad2a',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '37.228.117.247',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '37.228.117.247',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:06',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '37.228.117.247',
    Positive: true,
  },
  {
    id: 9,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 553,
    Certainty: 75,
    Severity: 50,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 195.123.238.36 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 7,
    CreatedAt: 'Tue Jan 11, 11:27:17',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '00588738-3e05-4137-b4ac-1c33721bda83',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '195.123.238.36',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.238.36',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:46',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.238.36',
    Positive: true,
  },
  {
    id: 10,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 552,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 185.250.204.126 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 9,
    CreatedAt: 'Tue Jan 11, 11:26:44',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd8eb4265-21f2-4fea-9a22-c776e1b42812',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '185.250.204.126',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '185.250.204.126',
    AdminState: 'IncidentReported',
    ActorisDest: 'null',
    LastModified: 'Tue Jan 11, 11:29:38',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '185.250.204.126',
    Positive: true,
  },
  {
    id: 11,
    Timestamp: 'Thu Jan 13, 12:57:38',
    CaseID: 931,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity Java Archive sent when remote host claims to send an image has been detected on source IP 23.227.189.102 to destination IP 192.168.1.107.',
    Category: 'Anomalous Activity',
    Score: 7,
    CreatedAt: 'Thu Jan 13, 12:08:48',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd8eb4265-21f2-4fea-9a22-c776e1b42812',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '23.227.189.102',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '23.227.189.102',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 15:33:49',
    ActorisDest: 'null',
    ActorIP: '192.168.1.107',
    Src: '192.168.1.107',
    EntityType: 'Ip',
    Entity: '23.227.189.102',
    Positive: true,
  },
  {
    id: 12,
    Timestamp: 'Thu Jan 13, 11:57:37',
    CaseID: 919,
    Certainty: 50,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Vulnerable Java Version 1.6.x Detected detected in a network session from source IP 192.168.1.107 to destination IP 23.227.189.102',
    Category: 'Vulnerability',
    Score: 8,
    CreatedAt: 'Thu Jan 13, 12:07:57',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'ee73f42c-f0c6-43fb-93c6-25f6a361a3e0',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.',
    Dest: '23.227.189.102',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '192.168.1.107',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 16:33:28',
    ActorisDest: 'null',
    ActorIP: '23.227.189.102',
    Src: '192.168.1.107',
    EntityType: 'Ip',
    Entity: '192.168.1.107',
    Positive: true,
  },
  {
    id: 13,
    Timestamp: 'Wed Jan 12, 20:20:03',
    CaseID: 875,
    Certainty: 75,
    Severity: 50,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Possible attack Possible CVE-2021-44228 Payload via LDAPv3 Response against 172.16.0.60 detected from 178.62.55.188',
    Category: 'Service Attack',
    Score: 9,
    CreatedAt: 'Wed Jan 12, 19:30:18',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'aacb17ba-c91d-4a67-9627-2cd160969ae4',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination',
    Dest: '172.16.0.60',
    Details:
      'Remote attackers are attempting to compromise a service. If vulnerabilities are successfully exploited, they could start lateral movement, data exfiltration, etc. We recommend examining the server logs for any signs of a potential compromise.',
    TargetIP: '172.16.0.60',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 19:30:30',
    ActorisDest: 'null',
    ActorIP: '178.62.55.188',
    Src: '178.62.55.188',
    EntityType: 'Ip',
    Entity: '172.16.0.60',
    Positive: true,
  },
  {
    id: 14,
    Timestamp: 'Wed Jan 12, 20:20:03',
    CaseID: 873,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Possible attack Possible CVE-2021-44228 Payload via LDAPv3 Response against 172.16.0.60 detected from 178.62.55.188',
    Category: 'Service Attack',
    Score: 10,
    CreatedAt: 'Wed Jan 12, 17:30:16',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '5f5fdaf0-3b54-4739-bf13-62c678804edf',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '172.16.0.60',
    Details:
      'Remote attackers are attempting to compromise a service. If vulnerabilities are successfully exploited, they could start lateral movement, data exfiltration, etc. We recommend examining the server logs for any signs of a potential compromise.',
    TargetIP: '172.16.0.60',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 19:30:24',
    ActorisDest: 'null',
    ActorIP: '178.62.55.188',
    Src: '178.62.55.188',
    EntityType: 'Ip',
    Entity: '178.62.55.188',
    Positive: true,
  },
  {
    id: 15,
    Timestamp: 'Tue Jan 11, 16:54:54',
    CaseID: 648,
    Certainty: 50,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex) has been detected on source IP 5.61.34.51 to destination IP 10.11.21.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 17:05:56',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '3dac7c9c-e861-4baa-8e6a-111663ae0b56',
    TargetSrc: 'null',
    Recommentation:
      'Verify if any of the following signs of infection are present (some might be missing due to the endpoint being outside of monitored network): suspicious/malicious file download, callback to C&C domain, suspicious activity on the system, unexpected outbound network activity from the source to internal/external hosts. If infection is confirmed, contact the user to take the endpoint offline for malware cleanup or reimage.',
    Dest: '10.11.21.101',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '5.61.34.51',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 17:05:56',
    ActorisDest: 'null',
    ActorIP: '10.11.21.101',
    Src: '5.61.34.51',
    EntityType: 'Ip',
    Entity: '5.61.34.51',
    Positive: true,
  },
  {
    id: 16,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 539,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 195.123.220.86 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 7,
    CreatedAt: 'Tue Jan 11, 11:22:43',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd2e7a925-26c2-485c-8a85-b2cdb97b21d8',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '195.123.220.86',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.220.86',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:19',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.220.86',
    Positive: true,
  },
  {
    id: 17,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 551,
    Certainty: 75,
    Severity: 100,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 37.228.117.247 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 11:22:43',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd2e7a925-26c2-485c-8a85-b2cdb97b21d8',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination',
    Dest: '195.123.220.86',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.220.86',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:19',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.220.86',
    Positive: true,
  },
  {
    id: 18,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 551,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 37.228.117.247 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 11:26:02',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '05fa9f13-c9b1-43a6-a6f7-c9818befad2a',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '37.228.117.247',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '37.228.117.247',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:06',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '37.228.117.247',
    Positive: true,
  },
  {
    id: 19,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 553,
    Certainty: 75,
    Severity: 50,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 195.123.238.36 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 7,
    CreatedAt: 'Tue Jan 11, 11:27:17',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '00588738-3e05-4137-b4ac-1c33721bda83',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '195.123.238.36',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.238.36',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:46',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.238.36',
    Positive: true,
  },
  {
    id: 20,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 552,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 185.250.204.126 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 9,
    CreatedAt: 'Tue Jan 11, 11:26:44',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd8eb4265-21f2-4fea-9a22-c776e1b42812',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '185.250.204.126',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '185.250.204.126',
    AdminState: 'IncidentReported',
    ActorisDest: 'null',
    LastModified: 'Tue Jan 11, 11:29:38',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '185.250.204.126',
    Positive: true,
  },
  {
    id: 21,
    Timestamp: 'Thu Jan 13, 12:57:38',
    CaseID: 921,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity Java Archive sent when remote host claims to send an image has been detected on source IP 23.227.189.102 to destination IP 192.168.1.107.',
    Category: 'Anomalous Activity',
    Score: 7,
    CreatedAt: 'Thu Jan 13, 12:08:48',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd8eb4265-21f2-4fea-9a22-c776e1b42812',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '23.227.189.102',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '23.227.189.102',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 15:33:49',
    ActorisDest: 'null',
    ActorIP: '192.168.1.107',
    Src: '192.168.1.107',
    EntityType: 'Ip',
    Entity: '23.227.189.102',
    Positive: true,
  },
  {
    id: 22,
    Timestamp: 'Thu Jan 13, 11:57:37',
    CaseID: 919,
    Certainty: 50,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Vulnerable Java Version 1.6.x Detected detected in a network session from source IP 192.168.1.107 to destination IP 23.227.189.102',
    Category: 'Vulnerability',
    Score: 8,
    CreatedAt: 'Thu Jan 13, 12:07:57',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'ee73f42c-f0c6-43fb-93c6-25f6a361a3e0',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.',
    Dest: '23.227.189.102',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '192.168.1.107',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 16:33:28',
    ActorisDest: 'null',
    ActorIP: '23.227.189.102',
    Src: '192.168.1.107',
    EntityType: 'Ip',
    Entity: '192.168.1.107',
    Positive: true,
  },
  {
    id: 23,
    Timestamp: 'Wed Jan 12, 20:20:03',
    CaseID: 875,
    Certainty: 75,
    Severity: 50,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Possible attack Possible CVE-2021-44228 Payload via LDAPv3 Response against 172.16.0.60 detected from 178.62.55.188',
    Category: 'Service Attack',
    Score: 9,
    CreatedAt: 'Wed Jan 12, 19:30:18',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'aacb17ba-c91d-4a67-9627-2cd160969ae4',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination',
    Dest: '172.16.0.60',
    Details:
      'Remote attackers are attempting to compromise a service. If vulnerabilities are successfully exploited, they could start lateral movement, data exfiltration, etc. We recommend examining the server logs for any signs of a potential compromise.',
    TargetIP: '172.16.0.60',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 19:30:30',
    ActorisDest: 'null',
    ActorIP: '178.62.55.188',
    Src: '178.62.55.188',
    EntityType: 'Ip',
    Entity: '172.16.0.60',
    Positive: true,
  },
  {
    id: 24,
    Timestamp: 'Wed Jan 12, 20:20:03',
    CaseID: 873,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Possible attack Possible CVE-2021-44228 Payload via LDAPv3 Response against 172.16.0.60 detected from 178.62.55.188',
    Category: 'Service Attack',
    Score: 10,
    CreatedAt: 'Wed Jan 12, 17:30:16',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '5f5fdaf0-3b54-4739-bf13-62c678804edf',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '172.16.0.60',
    Details:
      'Remote attackers are attempting to compromise a service. If vulnerabilities are successfully exploited, they could start lateral movement, data exfiltration, etc. We recommend examining the server logs for any signs of a potential compromise.',
    TargetIP: '172.16.0.60',
    AdminState: 'IncidentReported',
    LastModified: 'Thu Jan 13, 19:30:24',
    ActorisDest: 'null',
    ActorIP: '178.62.55.188',
    Src: '178.62.55.188',
    EntityType: 'Ip',
    Entity: '178.62.55.188',
    Positive: true,
  },
  {
    id: 25,
    Timestamp: 'Tue Jan 11, 16:54:54',
    CaseID: 648,
    Certainty: 50,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex) has been detected on source IP 5.61.34.51 to destination IP 10.11.21.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 17:05:56',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '3dac7c9c-e861-4baa-8e6a-111663ae0b56',
    TargetSrc: 'null',
    Recommentation:
      'Verify if any of the following signs of infection are present (some might be missing due to the endpoint being outside of monitored network): suspicious/malicious file download, callback to C&C domain, suspicious activity on the system, unexpected outbound network activity from the source to internal/external hosts. If infection is confirmed, contact the user to take the endpoint offline for malware cleanup or reimage.',
    Dest: '10.11.21.101',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '5.61.34.51',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 17:05:56',
    ActorisDest: 'null',
    ActorIP: '10.11.21.101',
    Src: '5.61.34.51',
    EntityType: 'Ip',
    Entity: '5.61.34.51',
    Positive: true,
  },
  {
    id: 26,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 539,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 195.123.220.86 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 7,
    CreatedAt: 'Tue Jan 11, 11:22:43',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd2e7a925-26c2-485c-8a85-b2cdb97b21d8',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '195.123.220.86',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.220.86',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:19',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.220.86',
    Positive: true,
  },
  {
    id: 27,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 551,
    Certainty: 75,
    Severity: 100,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 37.228.117.247 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 11:22:43',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd2e7a925-26c2-485c-8a85-b2cdb97b21d8',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination',
    Dest: '195.123.220.86',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.220.86',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:19',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.220.86',
    Positive: true,
  },
  {
    id: 28,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 551,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 37.228.117.247 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 8,
    CreatedAt: 'Tue Jan 11, 11:26:02',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '05fa9f13-c9b1-43a6-a6f7-c9818befad2a',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '37.228.117.247',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '37.228.117.247',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:06',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '37.228.117.247',
    Positive: true,
  },
  {
    id: 29,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 553,
    Certainty: 75,
    Severity: 50,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 195.123.238.36 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 7,
    CreatedAt: 'Tue Jan 11, 11:27:17',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '00588738-3e05-4137-b4ac-1c33721bda83',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '195.123.238.36',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '195.123.238.36',
    AdminState: 'IncidentReported',
    LastModified: 'Tue Jan 11, 11:28:46',
    ActorisDest: 'null',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '195.123.238.36',
    Positive: true,
  },
  {
    id: 30,
    Timestamp: 'Tue Jan 11, 11:12:34',
    CaseID: 552,
    Certainty: 100,
    Severity: 75,
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity ABUSE.CH SSL Blacklist Malicious SSL certificate detected (Dridex/Trickbot) has been detected on source IP 185.250.204.126 to destination IP 10.9.25.101',
    Category: 'Malware Compromise',
    Score: 9,
    CreatedAt: 'Tue Jan 11, 11:26:44',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'd8eb4265-21f2-4fea-9a22-c776e1b42812',
    TargetSrc: 'null',
    Recommentation:
      "Check the activity in question and ensure it's stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.",
    Dest: '185.250.204.126',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '185.250.204.126',
    AdminState: 'IncidentReported',
    ActorisDest: 'null',
    LastModified: 'Tue Jan 11, 11:29:38',
    ActorIP: '10.9.25.101',
    Src: '10.9.25.101',
    EntityType: 'Ip',
    Entity: '185.250.204.126',
    Positive: true,
  },
];

export const topCases = [
  {
    id: 1,
    Timestamp: 'Sun Feb 13, 00:04:26',
    CaseID: 3786,
    Certainty: 99,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '52.119.164.173',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Anomalous activity Unusual SSL certificate has been detected on source IP 10.6.1.163 to destination IP 52.119.164.173',
    Category: 'Anomalous Activity',
    Score: 3,
    ActorisDest: 'null',
    CreatedAt: 'Sun Feb 13, 01:10:24',
    EntryOrigin: 'Distributed Analytics Engine	',
    EntrySource: 'mnqa01',
    EntryType: 'SslAnomalyEvent',
    EntryUUID: '9f00076c-a8f4-4cc9-a7af-99cf22038d8a',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '52.119.164.173',
    Details:
      'We have detected an unexpected user activity. We recommend investigating this activity as it might lead to an unauthorized access to sensitive resources.',
    TargetIP: '10.6.1.163',
    LastModified: 'Sun Feb 13, 01:10:28',
    ActorIP: '52.119.164.173',
    Src: '10.6.1.163',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 2,
    Timestamp: 'Sun Feb 12, 12:24:48',
    CaseID: 3782,
    Certainty: 99,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '52.119.161.149',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Anomalous activity Unusual SSL certificate has been detected on source IP 10.6.1.163 to destination IP 52.119.161.149',
    Category: 'Anomalous Activity',
    Score: 3,
    ActorisDest: 'null',
    CreatedAt: 'Sun Feb 13, 13:10:22',
    EntryOrigin: 'Distributed Analytics Engine	',
    EntrySource: 'mnqa01',
    EntryType: 'SslAnomalyEvent',
    EntryUUID: '2410897f-6b9c-4345-b26b-3d0ed67edc06',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '52.119.161.149',
    Details:
      'We have detected an unexpected user activity. We recommend investigating this activity as it might lead to an unauthorized access to sensitive resources.',
    TargetIP: '10.6.1.163',
    LastModified: 'Sun Feb 12, 13:10:22',
    ActorIP: '52.119.161.163',
    Src: '10.6.1.163',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 3,
    Timestamp: 'Sat Feb 12, 12:24:48',
    CaseID: 3781,
    Certainty: 99,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '10.6.1.163',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Anomalous activity Unusual SSL certificate has been detected on source IP 10.6.1.163 to destination IP 52.119.161.149',
    Category: 'Anomalous Activity',
    Score: 3,
    ActorisDest: 'null',
    CreatedAt: 'Sat Feb 12, 13:10:20',
    EntryOrigin: 'Distributed Analytics Engine	',
    EntrySource: 'mnqa01',
    EntryType: 'SslAnomalyEvent',
    EntryUUID: '33ea96ff-f9a8-4374-b9af-4c7f6da1be15',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '52.119.161.149',
    Details:
      'We have detected an unexpected user activity. We recommend investigating this activity as it might lead to an unauthorized access to sensitive resources.',
    TargetIP: '10.6.1.163',
    LastModified: 'Sun Feb 13, 01:10:26',
    ActorIP: '52.119.161.149',
    Src: '10.6.1.163',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 4,
    Timestamp: 'Thu Feb 10, 10:48:00',
    CaseID: 3527,
    Certainty: 90,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '192.168.1.106',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'ET_KIT Possible Java Applet JNLP applet_ssv_validated Click To Run Bypass detected on source IP 5.149.255.102 to destination IP 192.168.1.106',
    Category: 'Suspicious Activity',
    Score: 3,
    ActorisDest: 'null',
    CreatedAt: 'Thu Feb 10, 10:01:57',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'dca4d4c8-ba31-433f-82f2-e74f1881dc0f',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment, use whitelist for specific source/destination.',
    Dest: '5.149.255.102',
    Details:
      'Potentially threatening activity detected. We recommend verifying context data to confirm if this might lead to a compromise.',
    TargetIP: '5.149.255.102',
    LastModified: 'Thu Feb 10, 11:30:25',
    ActorIP: '192.168.1.106',
    Src: '192.168.1.106',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 5,
    Timestamp: 'Thu Feb 10, 10:48:00',
    CaseID: 3528,
    Certainty: 90,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '5.149.255.102',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'ET_KIT Possible Java Applet JNLP applet_ssv_validated Click To Run Bypass detected on source IP 5.149.255.102 to destination IP 192.168.1.106',
    Category: 'Suspicious Activity',
    Score: 3,
    ActorisDest: 'null',
    CreatedAt: 'Thu Feb 10, 10:01:57',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '60dda7b8-f256-4876-931e-dc73954a4e41',
    TargetSrc: 'null',
    Recommentation:
      'Check the activity in question and ensure its stopped to enforce the company policy. If that activity alert is not applicable to the detected environment use whitelist for specific source/destination.',
    Dest: '5.149.255.102',
    Details:
      'Potentially threatening activity detected. We recommend verifying context data to confirm if this might lead to a compromise.',
    TargetIP: '5.149.255.102',
    LastModified: 'Thu Feb 10, 11:30:22',
    ActorIP: '192.168.1.106',
    Src: '192.168.1.106',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 6,
    Timestamp: 'Thu Feb 10, 10:01:58',
    CaseID: 3736,
    Certainty: 40,
    Severity: 75,
    AdminState: 'CaseOpen',
    Entity: '10.1.29.101',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity Microsoft Device Metadata Retrieval Client User-Agent has been detected on source IP 10.1.29.101 to destination IP 104.126.184.153.',
    Category: 'Malware Compromise',
    Score: 8,
    ActorisDest: 'null',
    CreatedAt: 'Thu Feb 10, 10:15:34',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: 'e727fc53-f709-474e-8034-cea83cd882eb',
    TargetSrc: 'null',
    Recommentation:
      'Check whether the callback was blocked on the firewall or by the endpoint protection tool (AV). Offending URL can be found under Sessions/Transactions view. Check Destination information to confirm the domain/network appears malicious. Retrieve the user endpoint or server for remediation/malware cleanup or full reimage.',
    Dest: '40.67.249.61',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '10.1.29.101',
    LastModified: 'Thu Feb 10, 10:15:38',
    ActorIP: '104.126.184.153',
    Src: '10.6.20.101',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 7,
    Timestamp: 'Thu Feb 10, 10:01:58',
    CaseID: 3537,
    Certainty: 40,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '40.67.249.61',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity Microsoft Device Metadata Retrieval Client User-Agent has been detected on source IP 10.1.29.101 to destination IP 40.67.249.61',
    Category: 'Malware Compromise',
    Score: 8,
    ActorisDest: 'null',
    CreatedAt: 'Thu Feb 10, 10:15:35',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '1eca331e-3ffd-4483-bece-005cea2ebd4e',
    TargetSrc: 'null',
    Recommentation:
      'Check whether the callback was blocked on the firewall or by the endpoint protection tool (AV). Offending URL can be found under Sessions/Transactions view. Check Destination information to confirm the domain/network appears malicious. Retrieve the user endpoint or server for remediation/malware cleanup or full reimage',
    Dest: '104.126.184.153',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '10.1.29.101',
    LastModified: 'Thu Feb 10, 10:15:35',
    ActorIP: '40.67.249.61',
    Src: '10.1.29.101',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 8,
    Timestamp: 'Thu Feb 10, 10:01:58',
    CaseID: 3538,
    Certainty: 40,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '104.126.184.153',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Malware activity Microsoft Device Metadata Retrieval Client User-Agent has been detected on source IP 10.1.29.101 to destination IP 104.126.184.153',
    Category: 'Malware Compromise',
    Score: 8,
    ActorisDest: 'null',
    CreatedAt: 'Thu Feb 10, 10:15:40',
    EntryOrigin: 'Rules Engine',
    EntrySource: 'lrmn5g',
    EntryType: 'AlertEvent',
    EntryUUID: '1eca331e-3ffd-4483-bece-005cea2ebd4e',
    TargetSrc: 'null',
    Recommentation:
      'Check whether the callback was blocked on the firewall or by the endpoint protection tool (AV). Offending URL can be found under Sessions/Transactions view. Check Destination information to confirm the domain/network appears malicious. Retrieve the user endpoint or server for remediation/malware cleanup or full reimage',
    Dest: '104.126.184.153',
    Details:
      "Network indicators suggest that the target user might be a victim of malware infection. We suggest running a malware scan and changing user's credentials if compromise is confirmed.",
    TargetIP: '10.1.29.101',
    LastModified: 'Thu Feb 10, 10:15:35',
    ActorIP: '40.67.249.61',
    Src: '10.1.29.101',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 9,
    Timestamp: 'Thu Feb 03, 04:00:25',
    CaseID: 2572,
    Certainty: 99,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '193.0.6.142',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Anomalous activity Unusual SSL certificate has been detected on source IP 10.6.0.71 to destination IP 193.0.6.142',
    Category: 'Anomalous Activity',
    Score: 3,
    ActorisDest: 'null',
    CreatedAt: 'Thu Feb 03, 05:10:26',
    EntryOrigin: 'Distributed Analytics Engine	',
    EntrySource: 'mnqa01',
    EntryType: 'SslAnomalyEvent',
    EntryUUID: 'd4806b8e-07e0-4d68-a0f0-b3545731ef10',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '193.0.6.142',
    Details:
      'We have detected an unexpected user activity. We recommend investigating this activity as it might lead to an unauthorized access to sensitive resources.',
    TargetIP: '10.6.1.71',
    LastModified: 'Thu Feb 03, 05:10:26',
    ActorIP: '193.0.6.142',
    Src: '10.6.0.71',
    EntityType: 'Ip',
    Positive: true,
  },
  {
    id: 10,
    Timestamp: 'Thu Feb 03, 04:00:25',
    CaseID: 2571,
    Certainty: 99,
    Severity: 25,
    AdminState: 'CaseOpen',
    Entity: '10.6.0.71',
    TargetUser: 'Unknown',
    TargetHost: 'Unknown',
    ActorUser: 'Unknown',
    ActorHost: 'Unknown',
    Summary:
      'Anomalous activity Unusual SSL certificate has been detected on source IP 10.6.0.71 to destination IP 193.0.6.142',
    Category: 'Anomalous Activity',
    Score: 3,
    ActorisDest: 'null',
    CreatedAt: 'Thu Feb 03, 05:10:23',
    EntryOrigin: 'Distributed Analytics Engine	',
    EntrySource: 'mnqa01',
    EntryType: 'SslAnomalyEvent',
    EntryUUID: 'ddcd7d8a-2977-4fb8-91ef-a7cfa29c8388',
    TargetSrc: 'null',
    Recommentation:
      'Confirm the vulnerability is present on the named devices and remediate it (usually by installing an updated version)',
    Dest: '193.0.6.142',
    Details:
      'We have detected an unexpected user activity. We recommend investigating this activity as it might lead to an unauthorized access to sensitive resources.',
    TargetIP: '10.6.1.71',
    LastModified: 'Thu Feb 03, 05:10:23',
    ActorIP: '193.0.6.142',
    Src: '10.6.0.71',
    EntityType: 'Ip',
    Positive: true,
  },
];
