export const CheckedWhiteList = {
  checkedSrcHost: false,
  checkedSrcUser: false,
  checkedDestHost: false,
  checkedCategory: false,
  checkedAttribute: false,
  checkedTrigger: false,
  checkedUri: false,
  checkedApp: false,
  checkedUserAgent: false,
  checkedEntrySrc: false,
  checkedEntryOrigin: false,
  checkedEntityType: false,
  checkedEventActorIP: false,
  checkedEventTargetsIP: false,
  checkedEventTargetsAction: false,
  checkedIndicator: false,
  checkedIndicatorType: false,
  checkedProtocol: false,
  checkedThreatLevel: false,
  checkedIncidentCaseEvent: false,
};

export const whiteListField = {
  src: '',
  srcHost: '',
  srcUser: '',
  dest: '',
  destHost: '',
  category: '',
  attribute: '',
  trigger: '',
  uri: '',
  app: '',
  userAgent: '',
  entrySrc: '',
  entryOrigin: '',
  entityType: '',
  eventActorIP: '',
  eventTargetsIP: '',
  eventTargetsAction: '',
  indicator: '',
  indicatorType: '',
  protocol: '',
  threatLevel: '',
  incidentCaseEvents: false,
};
